# -*- coding: utf-8 -*-
"""Titanic_accident.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12PV6QR5KhGrN4jvLhl5DiryvzJVbuFuH
"""

import pandas as pd
import numpy as nu

df = pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()

df.shape

df.isnull().sum()

drop_col = df.isnull().sum()[df.isnull().sum()>(80/100 * df.shape[0])]
drop_col

x = df.isnull().sum()

drop_col = x[x>(80/100 * df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index, axis=1, inplace=False)
df.isnull().sum()

df.fillna(df.mean(), inplace = False)
df.isnull().sum()

df['Embarked'].describe()

df['Embarked'].fillna('C',inplace=True)

df.isnull().sum()

df['Embarked'].describe()

df.corr()

df[['Parch','Fare']].corr()

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

df['Embarked'].fillna('C',inplace=True)

df.isnull().sum()

df.groupby(['Ticket'])['Survived'].mean()

df.corr()

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()